Repository sonata-project/EntityAuditBundle, pull requests merged in 2021-02, with the labels that each got.

#324 Update `AuditedCollection` in order to respect `Collection` interface
  src/Collection/AuditedCollection.php
  tests/Fixtures/Issue/Issue308User.php
  tests/IssueTest.php
Labels: patch

#355 Allow to use other connection and entity manager than "default"
  README.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SimpleThingsEntityAuditExtension.php
  src/Resources/config/auditable.xml
  tests/DependencyInjection/SimpleThingsEntityAuditExtensionTest.php
Labels: minor

#364 Add actions
  composer.json
  src/Action/CompareAction.php
  src/Action/IndexAction.php
  src/Action/ViewDetailAction.php
  src/Action/ViewEntityAction.php
  src/Action/ViewRevisionAction.php
  src/Controller/AuditController.php
  src/DependencyInjection/SimpleThingsEntityAuditExtension.php
  src/Resources/config/actions.xml
  src/Resources/config/routing.yml
Labels: minor

#363 Fix connection for doctrine event tag
  src/DependencyInjection/SimpleThingsEntityAuditExtension.php
  tests/DependencyInjection/SimpleThingsEntityAuditExtensionTest.php
Labels: patch

#369 corrected location of routing config file
  README.md
Labels: docs
