Repository sonata-project/EntityAuditBundle, pull requests merged in 2023-02, with the labels that each got.

#534 Fix audit revision query for enum column mapping
  src/EventListener/LogRevisionsListener.php
  tests/BaseTest.php
  tests/Fixtures/PHP81Issue/IssueEntityWithEnum.php
  tests/Fixtures/PHP81Issue/Status.php
  tests/Issue/IssueEntityWithEnumTest.php
Labels: patch

#537 Fix schema creation for self referencing many to many association
  src/EventListener/CreateSchemaListener.php
  tests/Fixtures/Relation/BaseSelfReferencingManyToManyEntity.php
  tests/Fixtures/Relation/SelfReferencingManyToManyEntity.php
  tests/Issue/IssueSelfReferencingManyToManyEntityTest.php
Labels: bug

#536 Add support for PSR clock
  composer.json
  src/AuditManager.php
  src/EventListener/LogRevisionsListener.php
  src/Resources/config/auditable.php
  tests/BaseTest.php
  tests/ClockTest.php
Labels: minor

#539 Fix not null constraint failed during many to many audit recording
  src/DeferredChangedManyToManyEntityRevisionToPersist.php
  src/EventListener/LogRevisionsListener.php
  tests/Fixtures/Relation/UnidirectionalManyToManyEntity.php
  tests/Fixtures/Relation/UnidirectionalManyToManyLinkedEntity.php
  tests/Issue/IssueUnidirectionalManyToManyEntityTest.php
Labels: patch

#544 Clear entity cache to prevent memory leak
  src/DependencyInjection/SimpleThingsEntityAuditExtension.php
  src/EventListener/CacheListener.php
  src/Resources/config/auditable.php
Labels: patch

#547 Allow doctrine/collections ^2.0
  composer.json
  phpstan-baseline.neon
  psalm.xml
  src/Collection/AuditedCollection.php
  src/EventListener/CreateSchemaListener.php
  tests/Fixtures/Issue/Issue308User.php
Labels: minor, dependencies
