Repository sonata-project/EntityAuditBundle, pull requests merged in 2023-04, with the labels that each got.

#564 Drop Symfony 4 and Twig 2
  .github/workflows/test-platforms.yaml
  .github/workflows/test.yaml
  composer.json
  src/Resources/config/actions.php
  src/Resources/config/auditable.php
  src/User/TokenStorageUsernameCallable.php
  tests/App/AppKernel.php
  tests/App/config/config.yml
  tests/App/config/config_symfony_v4.yml
  tests/App/config/config_symfony_v5.yml
  tests/App/config/config_symfony_v6.yml
Labels: minor

#573 DevKit updates for 1.x branch
  .github/workflows/auto-merge-dev-kit.yaml
Labels: automerge

#574 Fix CHANGELOG
  CHANGELOG.md
Labels: pedantic
