Repository sonata-project/EntityAuditBundle, pull requests merged in 2023-08, with the labels that each got.

#584 Do not rely on auto incremental ids
  tests/Fixtures/Relation/OwnedEntity2.php
  tests/RelationTest.php
Labels: pedantic

#583 use event_listener instead of event_subscriber
  src/DependencyInjection/SimpleThingsEntityAuditExtension.php
  src/EventListener/CacheListener.php
  src/EventListener/CreateSchemaListener.php
  src/EventListener/LogRevisionsListener.php
  src/Resources/config/auditable.php
  tests/DependencyInjection/SimpleThingsEntityAuditExtensionTest.php
Labels: patch

#586 DevKit updates for 1.x branch
  rector.php
Labels: automerge, dev-kit
