Repository sonata-project/EntityAuditBundle, pull requests merged in 2024-01, with the labels that each got.

#600 Updated rector to fix failing workflows.
  composer.json
Labels: pedantic

#599 Fix "diff" result for dates and other objects
  src/Utils/ArrayDiff.php
  tests/Utils/ArrayDiffTest.php
Labels: patch

#603 DevKit updates for 1.x branch
  phpstan.neon.dist
Labels: automerge, dev-kit
