Repository sonata-project/EntityAuditBundle, pull requests merged in 2024-06, with the labels that each got.

#625 Fix ci
  composer.json
  src/Collection/AuditedCollection.php
Labels: pedantic

#626 DevKit updates
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/test-platforms.yaml
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#627 Solve internal class usage
  src/DependencyInjection/SimpleThingsEntityAuditExtension.php
Labels: patch
